import { Send, Globe, MessageCircle, Users, Palette, Instagram, FileCheck } from "lucide-react";

export const PLATFORMS = [
  {
    code: "p1",
    name: "Telegram-канал",
    handle: "@stasroyce · 250",
    Icon: Send,
    role: "ЯДРО",
    verdict: "tune",
    roleLine: "Прогрев, витрина кейсов, сбор аудитории.",
    status: "250 подписчиков, контент «галерея + подпись».",
    tune: [
      "Лид-магнит в закреп",
      "Больше POV (80/20)",
      "Регулярность + перелинковка",
    ],
    leave: ["«Кейс + CTA» — ок"],
  },
  {
    code: "p2",
    name: "Сайт / портфолио",
    handle: "framer.website",
    Icon: Globe,
    role: "ВИТРИНА",
    verdict: "tune",
    roleLine: "Куда ведёшь: портфолио, цены, оффер.",
    status: "Есть, но с дырами.",
    tune: [
      "Битые ссылки в футере",
      "Свести позиционирование к одному",
      "Один спайк на первый экран",
      "Цены на пакет/результат",
      "Добавить метрики",
      "Вынести Yandex-кейс",
    ],
    leave: ["Структура и визуал — ок"],
  },
  {
    code: "p3",
    name: "Личка",
    handle: "@stas_royce",
    Icon: MessageCircle,
    role: "КОНВЕРСИЯ",
    verdict: "tune",
    roleLine: "Где идёт продажа.",
    status: "Работает, но без сценария.",
    tune: [
      "Скрипт первого ответа + квал",
      "Предоплата 50% по умолчанию",
    ],
    leave: ["Продажа в ЛС — верно"],
  },
  {
    code: "p4",
    name: "Чаты + конференции",
    handle: "главный канал ниши",
    Icon: Users,
    role: "ОХВАТ",
    verdict: "tune",
    roleLine: "Медиабайеры и арбитраж.",
    status: "Системно, вероятно, нет.",
    tune: [
      "3–5 чатов байеров + рассылки",
      "1–2 конфы (Affiliate World, SiGMA)",
    ],
    leave: ["Не распыляйся"],
  },
  {
    code: "p5",
    name: "Behance / Dribbble",
    handle: "ссылки битые",
    Icon: Palette,
    role: "ПРУФ",
    verdict: "fix",
    roleLine: "Пассивный вход для белой части.",
    status: "Ссылки ведут на x.com.",
    tune: [
      "Завести или убрать ссылки",
      "Белая часть (Yandex, UI/UX)",
    ],
    leave: ["Серое не пихать — NDA"],
  },
  {
    code: "p6",
    name: "Instagram",
    handle: "ссылка битая",
    Icon: Instagram,
    role: "ОХВАТ",
    verdict: "fix",
    roleLine: "Reels, но B2B-байер не тут.",
    status: "Ссылка битая.",
    tune: ["Системные reels или убрать пункт"],
    leave: ["Не приоритет"],
  },
  {
    code: "p7",
    name: "Блог / Read.cv",
    handle: "не подключено",
    Icon: FileCheck,
    role: "SEO",
    verdict: "fix",
    roleLine: "Мёртвые пункты; SEO позже.",
    status: "В меню есть, ссылок нет.",
    tune: [
      "Убрать мёртвые пункты",
      "Потом — блог под ASO",
    ],
    leave: ["Не сейчас"],
  },
];

export const VERDICT = {
  tune: { label: "докрутить", cls: "tune" },
  fix: { label: "чинить", cls: "fix" },
  skip: { label: "не заводить", cls: "skip" },
};
